version: '3'

services:
  redis:
    image: redis
    restart: always
    ports: 
      - "6379:6379"
    networks:
      - data-network

  mongo:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    networks:
      - data-network

  api:
    build: ./
    image: backend-api
    container_name: backend-api
    restart: always
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
    depends_on:
      - redis
    networks:
      - data-network

networks:
  data-network: